#############################################################################
# Makefile for building: BPA
# Generated by qmake (3.0) (Qt 5.3.0)
# Project:  BPA\BPA.pro
# Template: app
# Command: C:\DEV\qt\5.3\src\qtbase\bin\qmake.exe -spec win32-g++ CONFIG+=release -o Makefile BPA\BPA.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = C:\DEV\qt\5.3\src\qtbase\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: BPA/BPA.pro ../../../../DEV/qt/5.3/src/qtbase/mkspecs/features/spec_pre.prf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/qdevice.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/features/device_config.prf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/common/shell-win32.conf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/qconfig.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_lib_core.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_lib_core_private.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_lib_gui.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_lib_network.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_lib_network_private.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_lib_opengl.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_lib_sql.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_lib_testlib.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_lib_widgets.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_lib_xml.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_plugin_qico.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_plugin_qminimal.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_plugin_qnativewifibearer.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_plugin_qwindows.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_tool_qdoc.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_tool_qlalr.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_tool_syncqt.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/modules/qt_tool_uic.pri \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/features/qt_functions.prf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/features/qt_config.prf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/features/win32/qt_config.prf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/win32-g++/qmake.conf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/features/spec_post.prf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/features/exclusive_builds.prf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/features/default_pre.prf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/features/win32/default_pre.prf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/features/resolve_config.prf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/features/exclusive_builds_post.prf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/features/default_post.prf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/features/win32/rtti.prf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/features/precompile_header.prf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/features/warn_on.prf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/features/qt.prf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/features/resources.prf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/features/moc.prf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/features/win32/opengl.prf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/features/uic.prf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/features/win32/windows.prf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/features/testcase_targets.prf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/features/exceptions.prf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/features/yacc.prf \
		../../../../DEV/qt/5.3/src/qtbase/mkspecs/features/lex.prf \
		BPA/BPA.pro \
		C:/DEV/qt/5.3/src/qtbase/lib/Qt5Widgets.prl \
		C:/DEV/qt/5.3/src/qtbase/lib/Qt5Gui.prl \
		C:/DEV/qt/5.3/src/qtbase/lib/Qt5Core.prl \
		C:/DEV/qt/5.3/src/qtbase/plugins/accessible/qtaccessiblewidgets.prl \
		C:/DEV/qt/5.3/src/qtbase/plugins/platforms/qwindows.prl \
		C:/DEV/qt/5.3/src/qtbase/lib/Qt5PlatformSupport.prl \
		C:/DEV/qt/5.3/src/qtbase/plugins/imageformats/qico.prl
	$(QMAKE) -spec win32-g++ CONFIG+=release -o Makefile BPA\BPA.pro
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\features\spec_pre.prf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\qdevice.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\features\device_config.prf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\common\shell-win32.conf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\qconfig.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_lib_core.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_lib_core_private.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_lib_gui.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_lib_gui_private.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_lib_network.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_lib_network_private.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_lib_platformsupport_private.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_lib_sql.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_lib_sql_private.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_lib_xml.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_lib_xml_private.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_plugin_qgenericbearer.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_plugin_qico.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_plugin_qminimal.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_plugin_qnativewifibearer.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_plugin_qoffscreen.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_plugin_qtaccessiblewidgets.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_plugin_qwindows.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_plugin_windowsprintersupport.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_tool_qdoc.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_tool_qlalr.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_tool_syncqt.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\modules\qt_tool_uic.pri:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\features\qt_functions.prf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\features\qt_config.prf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\features\win32\qt_config.prf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\win32-g++\qmake.conf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\features\spec_post.prf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\features\exclusive_builds.prf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\features\default_pre.prf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\features\win32\default_pre.prf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\features\resolve_config.prf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\features\exclusive_builds_post.prf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\features\default_post.prf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\features\win32\rtti.prf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\features\precompile_header.prf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\features\warn_on.prf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\features\qt.prf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\features\resources.prf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\features\moc.prf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\features\win32\opengl.prf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\features\uic.prf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\features\win32\windows.prf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\features\testcase_targets.prf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\features\exceptions.prf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\features\yacc.prf:
..\..\..\..\DEV\qt\5.3\src\qtbase\mkspecs\features\lex.prf:
BPA\BPA.pro:
C:/DEV/qt/5.3/src/qtbase/lib/Qt5Widgets.prl:
C:/DEV/qt/5.3/src/qtbase/lib/Qt5Gui.prl:
C:/DEV/qt/5.3/src/qtbase/lib/Qt5Core.prl:
C:/DEV/qt/5.3/src/qtbase/plugins/accessible/qtaccessiblewidgets.prl:
C:/DEV/qt/5.3/src/qtbase/plugins/platforms/qwindows.prl:
C:/DEV/qt/5.3/src/qtbase/lib/Qt5PlatformSupport.prl:
C:/DEV/qt/5.3/src/qtbase/plugins/imageformats/qico.prl:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ CONFIG+=release -o Makefile BPA\BPA.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) C:\Users\User\Desktop\BPAQTv2\bpa_plugin_import.cpp

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
